// <auto-generated />
using System;
using AppBackend.BusinessObjects.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppBackend.BusinessObjects.Migrations
{
    [DbContext(typeof(IOTShowroomContext))]
    partial class IOTShowroomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("announcement_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("TargetAudience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("target_audience");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId")
                        .HasName("PK__Announce__C640A82D80ABE06F");

                    b.HasIndex("AdminId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("class_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructor_id");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__FDF47986C6BBE5E5");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ClassEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("EnrolledAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("enrolled_at");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Class_En__6D24AA7A09B7DB62");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "ClassId", "StudentId" }, "uq_class_student")
                        .IsUnique()
                        .HasFilter("[class_id] IS NOT NULL AND [student_id] IS NOT NULL");

                    b.ToTable("Class_Enrollments");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("evaluation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<DateTime?>("EvaluatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("instructor_id");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_score");

                    b.HasKey("EvaluationId")
                        .HasName("PK__Evaluati__827C592D4FC39243");

                    b.HasIndex("InstructorId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.EvaluationDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int?>("EvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("evaluation_id");

                    b.Property<int?>("RubricId")
                        .HasColumnType("int")
                        .HasColumnName("rubric_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("score");

                    b.HasKey("DetailId")
                        .HasName("PK__Evaluati__38E9A224263B5411");

                    b.HasIndex("RubricId");

                    b.HasIndex(new[] { "EvaluationId", "RubricId" }, "uq_eval_rubric")
                        .IsUnique()
                        .HasFilter("[evaluation_id] IS NOT NULL AND [rubric_id] IS NOT NULL");

                    b.ToTable("Evaluation_Details");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.HallOfFame", b =>
                {
                    b.Property<int>("HofId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hof_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HofId"));

                    b.Property<DateTime?>("NominatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("nominated_at");

                    b.Property<int?>("NominatedBy")
                        .HasColumnType("int")
                        .HasColumnName("nominated_by");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    b.HasKey("HofId")
                        .HasName("PK__Hall_of___A7FA0EFE9BDCBBC9");

                    b.HasIndex("SemesterId");

                    b.HasIndex(new[] { "ProjectId", "SemesterId" }, "uq_project_semester")
                        .IsUnique()
                        .HasFilter("[project_id] IS NOT NULL AND [semester_id] IS NOT NULL");

                    b.ToTable("Hall_of_Fame");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.LiveDemo", b =>
                {
                    b.Property<int>("DemoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("demo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DemoId"));

                    b.Property<string>("DemoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("demo_url");

                    b.Property<DateTime?>("EndedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("ended_at");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Protocol")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("protocol");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("started_at");

                    b.HasKey("DemoId")
                        .HasName("PK__Live_Dem__A77EA3F0ACFB453A");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SensorId");

                    b.ToTable("Live_Demo");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.LiveDemoSensor", b =>
                {
                    b.Property<int>("LdsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lds_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LdsId"));

                    b.Property<int>("DemoId")
                        .HasColumnType("int")
                        .HasColumnName("demo_id");

                    b.Property<int>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.HasKey("LdsId")
                        .HasName("PK__Live_Dem__A3A7250B504BC41A");

                    b.HasIndex("SensorId");

                    b.HasIndex(new[] { "DemoId", "SensorId" }, "uq_demo_sensor")
                        .IsUnique();

                    b.ToTable("Live_Demo_Sensors");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiver_id");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("SentAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("sent_at");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__0BBF6EE61FA26B94");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842F65AEF100");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int")
                        .HasColumnName("leader_id");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.HasKey("ProjectId")
                        .HasName("PK__Projects__BC799E1F4515E28E");

                    b.HasIndex("ClassId");

                    b.HasIndex("LeaderId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectApprovalHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime?>("ActedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("acted_at");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("action");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int")
                        .HasColumnName("reviewer_id");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.HasKey("HistoryId")
                        .HasName("PK__Project___096AA2E9E3530770");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Project_Approval_History");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("asset_type");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("FileExt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_ext");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_url");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mime_type");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UploadedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video_url");

                    b.Property<string>("Visibility")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("visibility");

                    b.HasKey("AssetId")
                        .HasName("PK__Project___D28B561D5D4D7819");

                    b.HasIndex(new[] { "ProjectId" }, "idx_assets_project");

                    b.HasIndex(new[] { "AssetType", "Visibility" }, "idx_assets_type");

                    b.ToTable("Project_Assets");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("member_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("RoleInProject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role_in_project");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("MemberId")
                        .HasName("PK__Project___B29B85342BF23F4F");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ProjectId", "UserId" }, "uq_project_user")
                        .IsUnique()
                        .HasFilter("[project_id] IS NOT NULL AND [user_id] IS NOT NULL");

                    b.ToTable("Project_Members");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectMilestone", b =>
                {
                    b.Property<int>("MilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("milestone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MilestoneId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.HasKey("MilestoneId")
                        .HasName("PK__Project___67592EB7BCF1E706");

                    b.HasIndex(new[] { "ProjectId" }, "IX_Project_Milestones_Project");

                    b.ToTable("Project_Milestones");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("int")
                        .HasColumnName("submitted_by");

                    b.HasKey("SubmissionId")
                        .HasName("PK__Project___9B53559522FF4404");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SubmittedBy");

                    b.ToTable("Project_Submissions");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__760965CCE3CEA0C6");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Rubric", b =>
                {
                    b.Property<int>("RubricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rubric_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RubricId"));

                    b.Property<string>("CriteriaName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("criteria_name");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("max_score");

                    b.HasKey("RubricId")
                        .HasName("PK__Rubrics__A1FB3B3A54CA5B29");

                    b.ToTable("Rubrics");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.RubricWeight", b =>
                {
                    b.Property<int>("WeightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("weight_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeightId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("RubricId")
                        .HasColumnType("int")
                        .HasColumnName("rubric_id");

                    b.Property<decimal>("WeightRatio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("weight_ratio");

                    b.HasKey("WeightId")
                        .HasName("PK__Rubric_W__453932ACE56F44E9");

                    b.HasIndex("RubricId");

                    b.HasIndex(new[] { "ClassId", "RubricId" }, "uq_class_rubric")
                        .IsUnique();

                    b.ToTable("Rubric_Weights");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("semester_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Term")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("term");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__CBC81B01BEC31556");

                    b.HasIndex(new[] { "Code" }, "UQ__Semester__357D4CF91CF41FDF")
                        .IsUnique();

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unit");

                    b.HasKey("SensorId")
                        .HasName("PK__sensors__1A8E906028A273BE");

                    b.HasIndex(new[] { "ProjectId" }, "IX_sensors_project_id");

                    b.ToTable("sensors");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.SensorDatum", b =>
                {
                    b.Property<long>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("data_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DataId"));

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_payload");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Timestamp")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("timestamp");

                    b.Property<double?>("Value")
                        .HasColumnType("float")
                        .HasColumnName("value");

                    b.HasKey("DataId")
                        .HasName("PK__sensor_d__F5A76B3B81CAD6A5");

                    b.HasIndex(new[] { "SensorId", "Timestamp" }, "idx_sensor_ts");

                    b.ToTable("sensor_data");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("phone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F77954EFA");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164D0B4B9B9")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Announcement", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Admin")
                        .WithMany("Announcements")
                        .HasForeignKey("AdminId")
                        .HasConstraintName("FK_Announcements_Admin");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Class", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Instructor")
                        .WithMany("Classes")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK_Classes_Instructor");

                    b.HasOne("AppBackend.BusinessObjects.Models.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK_Classes_Semester");

                    b.Navigation("Instructor");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ClassEnrollment", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Class", "Class")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Enrollments_Class");

                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Student")
                        .WithMany("ClassEnrollments")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Enrollments_Student");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Evaluation", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Instructor")
                        .WithMany("Evaluations")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK_Evaluations_Instructor");

                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("Evaluations")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Evaluations_Project");

                    b.Navigation("Instructor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.EvaluationDetail", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Evaluation", "Evaluation")
                        .WithMany("EvaluationDetails")
                        .HasForeignKey("EvaluationId")
                        .HasConstraintName("FK_EvalDetails_Evaluation");

                    b.HasOne("AppBackend.BusinessObjects.Models.Rubric", "Rubric")
                        .WithMany("EvaluationDetails")
                        .HasForeignKey("RubricId")
                        .HasConstraintName("FK_EvalDetails_Rubric");

                    b.Navigation("Evaluation");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.HallOfFame", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("HallOfFames")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_HOF_Project");

                    b.HasOne("AppBackend.BusinessObjects.Models.Semester", "Semester")
                        .WithMany("HallOfFames")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK_HOF_Semester");

                    b.Navigation("Project");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.LiveDemo", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("LiveDemos")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_LiveDemo_Project");

                    b.HasOne("AppBackend.BusinessObjects.Models.Sensor", "Sensor")
                        .WithMany("LiveDemos")
                        .HasForeignKey("SensorId")
                        .HasConstraintName("FK_LiveDemo_Sensor");

                    b.Navigation("Project");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.LiveDemoSensor", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.LiveDemo", "Demo")
                        .WithMany("LiveDemoSensors")
                        .HasForeignKey("DemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LDS_Demo");

                    b.HasOne("AppBackend.BusinessObjects.Models.Sensor", "Sensor")
                        .WithMany("LiveDemoSensors")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LDS_Sensor");

                    b.Navigation("Demo");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Message", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_Messages_Receiver");

                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Messages_Sender");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Notification", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Project", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Class", "Class")
                        .WithMany("Projects")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Projects_Class");

                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Leader")
                        .WithMany("Projects")
                        .HasForeignKey("LeaderId")
                        .HasConstraintName("FK_Projects_Leader");

                    b.Navigation("Class");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectApprovalHistory", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.User", "Reviewer")
                        .WithMany("ProjectApprovalHistories")
                        .HasForeignKey("ReviewerId")
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalHistory_Reviewer");

                    b.HasOne("AppBackend.BusinessObjects.Models.ProjectSubmission", "Submission")
                        .WithMany("ProjectApprovalHistories")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalHistory_Submission");

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectAsset", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("ProjectAssets")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Project_Assets_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectMember", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_Project_Members_Project");

                    b.HasOne("AppBackend.BusinessObjects.Models.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Project_Members_User");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectMilestone", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("ProjectMilestones")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Project_Milestones_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectSubmission", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("ProjectSubmissions")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_Project");

                    b.HasOne("AppBackend.BusinessObjects.Models.User", "SubmittedByNavigation")
                        .WithMany("ProjectSubmissions")
                        .HasForeignKey("SubmittedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Submissions_User");

                    b.Navigation("Project");

                    b.Navigation("SubmittedByNavigation");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.RubricWeight", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Class", "Class")
                        .WithMany("RubricWeights")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_RubricWeights_Class");

                    b.HasOne("AppBackend.BusinessObjects.Models.Rubric", "Rubric")
                        .WithMany("RubricWeights")
                        .HasForeignKey("RubricId")
                        .IsRequired()
                        .HasConstraintName("FK_RubricWeights_Rubric");

                    b.Navigation("Class");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Sensor", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Project", "Project")
                        .WithMany("Sensors")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("FK_sensors_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.SensorDatum", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Sensor", "Sensor")
                        .WithMany("SensorData")
                        .HasForeignKey("SensorId")
                        .HasConstraintName("FK_sensor_data_Sensor");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.User", b =>
                {
                    b.HasOne("AppBackend.BusinessObjects.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Class", b =>
                {
                    b.Navigation("ClassEnrollments");

                    b.Navigation("Projects");

                    b.Navigation("RubricWeights");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Evaluation", b =>
                {
                    b.Navigation("EvaluationDetails");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.LiveDemo", b =>
                {
                    b.Navigation("LiveDemoSensors");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Project", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("HallOfFames");

                    b.Navigation("LiveDemos");

                    b.Navigation("ProjectAssets");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectMilestones");

                    b.Navigation("ProjectSubmissions");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.ProjectSubmission", b =>
                {
                    b.Navigation("ProjectApprovalHistories");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Rubric", b =>
                {
                    b.Navigation("EvaluationDetails");

                    b.Navigation("RubricWeights");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Semester", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("HallOfFames");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.Sensor", b =>
                {
                    b.Navigation("LiveDemoSensors");

                    b.Navigation("LiveDemos");

                    b.Navigation("SensorData");
                });

            modelBuilder.Entity("AppBackend.BusinessObjects.Models.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("ClassEnrollments");

                    b.Navigation("Classes");

                    b.Navigation("Evaluations");

                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("Notifications");

                    b.Navigation("ProjectApprovalHistories");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectSubmissions");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
